const isElectron = window.api !== undefined;

const getAppHeight = () => {
  if (typeof window !== 'undefined' && /Mobi|Android/i.test(navigator.userAgent)) {
    return `${window.innerHeight}px`;
  }
  return isElectron ? 'calc(100vh - 30px)' : '100vh';
};

// Premium Design System Colors
const colors = {
  bgDeep: '#0a0a0f',
  bgPrimary: '#12121a',
  bgSecondary: '#1a1a25',
  bgElevated: '#222230',
  glassBg: 'rgba(255, 255, 255, 0.03)',
  glassBgHover: 'rgba(255, 255, 255, 0.06)',
  glassBorder: 'rgba(255, 255, 255, 0.08)',
  glassBorderHover: 'rgba(255, 255, 255, 0.15)',
  accentPrimary: '#8b5cf6',
  accentSecondary: '#06b6d4',
  textPrimary: 'rgba(255, 255, 255, 0.95)',
  textSecondary: 'rgba(255, 255, 255, 0.65)',
  textMuted: 'rgba(255, 255, 255, 0.4)',
};

export const layoutStyles = {
  appContainer: {
    width: '100vw',
    height: getAppHeight(),
    bg: colors.bgDeep,
    color: colors.textPrimary,
    overflow: 'hidden',
    position: 'relative',
    display: 'flex',
    flexDirection: { base: 'column', md: 'row' },
    mt: isElectron ? '30px' : '0',
  },
  sidebar: {
    position: 'relative' as const,
    width: { base: '100%', md: '380px' },
    height: { base: 'auto', md: '100%' },
    bg: colors.bgPrimary,
    borderRight: '1px solid',
    borderColor: colors.glassBorder,
    overflow: 'hidden',
    flexShrink: 0,
    transition: 'all 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
    backdropFilter: 'blur(20px)',
  },
  mainContent: {
    flex: 1,
    height: { base: 'calc(100% - 120px)', md: '100%' },
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    transition: 'all 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
    width: '100%',
    overflow: 'hidden',
    bg: 'transparent',
  },
  canvas: {
    position: 'relative',
    width: '100%',
    flex: 1,
    transition: 'all 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
    overflow: 'hidden',
    willChange: 'transform',
  },
  footer: {
    width: '100%',
    height: { base: '100px', md: '110px' },
    transition: 'all 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
    willChange: 'transform',
    position: 'relative',
    zIndex: 1,
  },
  toggleButton: {
    position: 'absolute',
    left: 0,
    top: '50%',
    transform: 'translateY(-50%)',
    height: '60px',
    bg: colors.glassBg,
    _hover: { 
      bg: colors.glassBgHover,
      borderColor: colors.accentPrimary,
    },
    borderLeftRadius: 0,
    borderRightRadius: 'lg',
    zIndex: 10,
    border: '1px solid',
    borderColor: colors.glassBorder,
    borderLeft: 'none',
    transition: 'all 0.25s ease',
  },
  canvasHeight: (isFooterCollapsed: boolean) => ({
    height: isFooterCollapsed ? 'calc(100% - 24px)' : 'calc(100% - 110px)',
  }),
  sidebarToggleButton: {
    position: 'absolute',
    left: 0,
    top: '50%',
    transform: 'translateY(-50%)',
    height: '60px',
    bg: colors.bgPrimary,
    borderLeftRadius: 0,
    borderRightRadius: 'lg',
    zIndex: 10,
    border: '1px solid',
    borderColor: colors.glassBorder,
    borderLeft: 'none',
  },
  collapsedFooter: {
    height: { base: '20px', md: '24px' },
    transition: 'all 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  windowsTitleBar: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: '30px',
    backgroundColor: colors.bgDeep,
    borderBottom: '1px solid',
    borderColor: colors.glassBorder,
    paddingX: '10px',
    zIndex: 1000,
    css: { '-webkit-app-region': 'drag' },
  },
  macTitleBar: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '30px',
    backgroundColor: colors.bgDeep,
    borderBottom: '1px solid',
    borderColor: colors.glassBorder,
    zIndex: 1000,
    css: {
      '-webkit-app-region': 'drag',
      '-webkit-user-select': 'none',
    },
  },
  titleBarTitle: {
    fontSize: 'sm',
    color: colors.textSecondary,
    textAlign: 'center',
    fontWeight: '500',
    letterSpacing: '0.5px',
  },
  titleBarButtons: {
    display: 'flex',
    gap: '1',
  },
  titleBarButton: {
    size: 'sm',
    variant: 'ghost',
    color: colors.textSecondary,
    css: { '-webkit-app-region': 'no-drag' },
    _hover: { 
      backgroundColor: colors.glassBgHover,
      color: colors.textPrimary,
    },
    borderRadius: 'md',
    transition: 'all 0.15s ease',
  },
  closeButton: {
    size: 'sm',
    variant: 'ghost',
    color: colors.textSecondary,
    css: { '-webkit-app-region': 'no-drag' },
    _hover: { 
      backgroundColor: '#ef4444',
      color: 'white',
    },
    borderRadius: 'md',
    transition: 'all 0.15s ease',
  },
} as const;
